"""add doctor_patient association

Revision ID: 151ab0c23fbf
Revises: f7dd6bf3d806
Create Date: 2026-02-18 14:59:10.341041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151ab0c23fbf'
down_revision: Union[str, Sequence[str], None] = 'f7dd6bf3d806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patient',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'patient_id')
    )
    op.add_column('doctors', sa.Column('specialization', sa.String(), nullable=False))
    op.drop_column('doctors', 'specialty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialty', sa.VARCHAR(), nullable=False))
    op.drop_column('doctors', 'specialization')
    op.drop_table('doctor_patient')
    # ### end Alembic commands ###
